// AUTO-GENERATED by scripts/generate-compositions.mjs — do not edit by hand
// Run: npm run gen
import type { CustomerStoryData } from "./CustomerStory/schema";

export const CUSTOMERS: Array<{ id: string; folder: string; data: CustomerStoryData }> = [
  {
    id: "Alertora",
    folder: "alertora",
    data: {
        "customerName": "Alertora",
        "tagline": "AI-Powered WhatsApp Safety Companion for Solo Travelers",
        "accentColor": "#10B981",
        "challenge": {
            "headline": "Fragmented travel info leaves solo travelers exposed",
            "description": "Solo travelers relied on multiple scattered sources to gather destination-specific guidance, making it time-consuming and stressful to access critical information quickly. This fragmented approach created unnecessary friction and overwhelm during the moments travelers needed support most.",
            "screenshot": "customers/alertora/1.png"
        },
        "features": [
            {
                "screenshot": "customers/alertora/2.png",
                "label": "Real Scenario Guidance"
            },
            {
                "screenshot": "customers/alertora/3.png",
                "label": "WhatsApp Onboarding Flow"
            },
            {
                "screenshot": "customers/alertora/4.png",
                "label": "Safety Features Suite"
            },
            {
                "screenshot": "customers/alertora/5.png",
                "label": "Traveler Community Stats"
            },
            {
                "screenshot": "customers/alertora/6.png",
                "label": "User Testimonials Wall"
            }
        ],
        "result": {
            "headline": "Travelers explore with confidence, not anxiety",
            "stats": [
                {
                    "value": "1,000+",
                    "label": "Solo Travelers Supported"
                },
                {
                    "value": "24/7",
                    "label": "On-Demand Guidance"
                },
                {
                    "value": "Zero",
                    "label": "Extra Apps Needed"
                }
            ],
            "quote": "By reducing friction in accessing travel-related information, Alertora helps users make more informed decisions and approach unfamiliar situations with greater confidence.",
            "authorName": "Alertora",
            "authorTitle": "Travel Safety / AI Chatbots",
            "screenshot": "customers/alertora/7.png"
        }
    },
  },
  {
    id: "Axirify",
    folder: "axirify",
    data: {
        "customerName": "Axirify",
        "tagline": "AI-Powered Automation Platform for Clinics & Med Spas",
        "accentColor": "#6366F1",
        "challenge": {
            "headline": "Clinics losing leads to slow, manual processes",
            "description": "Property and clinic businesses relied on multiple disconnected systems, causing fragmented workflows, duplicate data entry, and missed opportunities. As teams grew, managing information consistently across functions became increasingly unmanageable.",
            "screenshot": "customers/axirify/1.png"
        },
        "features": [
            {
                "screenshot": "customers/axirify/2.png",
                "label": "Unified Operations Dashboard"
            },
            {
                "screenshot": "customers/axirify/3.png",
                "label": "Pain Points Overview"
            },
            {
                "screenshot": "customers/axirify/4.png",
                "label": "Front Office Automation"
            },
            {
                "screenshot": "customers/axirify/5.png",
                "label": "How It Works Flow"
            },
            {
                "screenshot": "customers/axirify/6.png",
                "label": "WhatsApp & Stripe Integrations"
            },
            {
                "screenshot": "customers/axirify/7.png",
                "label": "Proven ROI Stats"
            }
        ],
        "result": {
            "headline": "5x ROI and 40+ hours saved every month",
            "stats": [
                {
                    "value": "5x",
                    "label": "Total ROI (conservative)"
                },
                {
                    "value": "40+",
                    "label": "Hours Saved Per Month"
                },
                {
                    "value": "100+",
                    "label": "More Appointments Confirmed"
                }
            ],
            "quote": "One client recovered $5,000 USD/month in lost appointments from faster follow-ups alone. Property management, CRM, and project management now live in a single platform instead of multiple disconnected tools.",
            "authorName": "Axirify",
            "authorTitle": "Property & Operations Management SaaS Platform",
            "screenshot": "customers/axirify/8.png"
        }
    },
  },
  {
    id: "BacklinkBrain",
    folder: "backlink-brain",
    data: {
        "customerName": "Backlink Brain",
        "tagline": "AI-Powered Outreach Platform for SEO Backlink Discovery and Campaign Management",
        "accentColor": "#F59E0B",
        "challenge": {
            "headline": "Manual outreach limits scale and efficiency",
            "description": "SEO professionals juggled multiple tools and repetitive processes while trying to execute campaigns at scale. Maintaining consistency and tracking progress across multiple initiatives made it nearly impossible to grow efficiently.",
            "screenshot": "customers/backlink-brain/1.png"
        },
        "features": [
            {
                "screenshot": "customers/backlink-brain/2.png",
                "label": "PitchBox Integration"
            },
            {
                "screenshot": "customers/backlink-brain/3.png",
                "label": "3-Step Campaign Onboarding"
            },
            {
                "screenshot": "customers/backlink-brain/4.png",
                "label": "Target Audience Benefits"
            },
            {
                "screenshot": "customers/backlink-brain/5.png",
                "label": "User Success Stories"
            },
            {
                "screenshot": "customers/backlink-brain/6.png",
                "label": "Contact Export Sheet"
            }
        ],
        "result": {
            "headline": "Launched on web and mobile with 99+ users",
            "stats": [
                {
                    "value": "99+",
                    "label": "Active Users"
                },
                {
                    "value": "1",
                    "label": "Unified Platform"
                },
                {
                    "value": "AI",
                    "label": "Opportunity Discovery"
                }
            ],
            "quote": "By simplifying workflows and reducing manual effort, Backlink Brain supports improved productivity and enables users to scale their activities with greater confidence.",
            "authorName": "Backlink Brain",
            "authorTitle": "SEO / AI Marketing Platform",
            "screenshot": "customers/backlink-brain/7.png"
        }
    },
  },
  {
    id: "CeTax",
    folder: "ce-tax",
    data: {
        "customerName": "CE Tax",
        "tagline": "Unified financial management system for invoicing, transactions & compliance",
        "accentColor": "#3B82F6",
        "challenge": {
            "headline": "Fragmented finance tools create costly gaps",
            "description": "Growing businesses managed invoices, transactions, and reporting across separate disconnected tools — creating administrative overhead and limiting financial visibility. The fragmentation made it difficult to maintain accurate, timely financial records at scale.",
            "screenshot": "customers/ce-tax/1.png"
        },
        "features": [
            {
                "screenshot": "customers/ce-tax/2.png",
                "label": "Unified Features Overview"
            }
        ],
        "result": {
            "headline": "Centralized, confident financial management",
            "stats": [
                {
                    "value": "1",
                    "label": "Unified Platform"
                },
                {
                    "value": "Zero",
                    "label": "Fragmented Processes"
                },
                {
                    "value": "100%",
                    "label": "Centralized Records"
                }
            ],
            "quote": "CE Tax enables businesses to work more effectively and maintain greater confidence in their financial operations.",
            "authorName": "CE Tax",
            "authorTitle": "Tax & Compliance Financial Software",
            "screenshot": "customers/ce-tax/3.png"
        }
    },
  },
  {
    id: "Celleasy",
    folder: "celleasy",
    data: {
        "customerName": "CellEasy",
        "tagline": "E-commerce platform for Rogers dealers with sales attribution & tracking",
        "accentColor": "#EF4444",
        "challenge": {
            "headline": "No way to track which rep made each online sale",
            "description": "Standard e-commerce platforms couldn't attribute sales to individual representatives, making it impossible for Rogers dealers to measure team performance or distribute commissions fairly. Managing complex telecom product catalogs with carrier plans, devices, and accessories added further operational strain.",
            "screenshot": "customers/celleasy/1.png"
        },
        "features": [
            {
                "screenshot": "customers/celleasy/2.png",
                "label": "Featured Deals Showcase"
            },
            {
                "screenshot": "customers/celleasy/3.png",
                "label": "Customer Navigation Hub"
            }
        ],
        "result": {
            "headline": "Digital commerce built for dealer teams",
            "stats": [
                {
                    "value": "100%",
                    "label": "Sales Attribution"
                },
                {
                    "value": "Zero",
                    "label": "Commission Disputes"
                },
                {
                    "value": "1",
                    "label": "Unified Platform"
                }
            ],
            "quote": "CellEasy bridged the gap between traditional retail sales structures and digital commerce, improving visibility into team performance and creating a more structured and scalable approach to wireless retail distribution.",
            "authorName": "CellEasy",
            "authorTitle": "Wireless Retail E-Commerce Platform",
            "screenshot": "customers/celleasy/4.png"
        }
    },
  },
  {
    id: "Dare",
    folder: "dare",
    data: {
        "customerName": "DARE",
        "tagline": "Agentic AI Research Platform for Scientists and PhD Researchers",
        "accentColor": "#8B5CF6",
        "challenge": {
            "headline": "Advanced AI was locked behind engineering expertise",
            "description": "Scientists who needed AI agents to process massive datasets or run complex analysis workflows faced steep technical barriers without dedicated engineering support. Sending sensitive research data to commercial AI platforms also violated institutional data policies.",
            "screenshot": "customers/dare/1.png"
        },
        "features": [
            {
                "screenshot": "customers/dare/2.png",
                "label": "Self-Hosted Architecture"
            },
            {
                "screenshot": "customers/dare/3.png",
                "label": "Multi-Audience Platform"
            },
            {
                "screenshot": "customers/dare/4.png",
                "label": "Workflow Builder Tools"
            }
        ],
        "result": {
            "headline": "AI research democratized at Carnegie Mellon",
            "stats": [
                {
                    "value": "2,000+",
                    "label": "Students Served"
                },
                {
                    "value": "Multi-school",
                    "label": "Collaborations Underway"
                },
                {
                    "value": "100%",
                    "label": "Data Stays In-House"
                }
            ],
            "quote": "DARE has transformed AI-powered research from an engineering challenge into an accessible tool for scientific discovery. Deployed at Carnegie Mellon University, it now accelerates AI-powered research across multiple disciplines.",
            "authorName": "DARE",
            "authorTitle": "AI Research Platform, Academia & Non-Profits",
            "screenshot": "customers/dare/5.png"
        }
    },
  },
  {
    id: "GoldSellingStandards",
    folder: "gold-selling-standards",
    data: {
        "customerName": "Gold Selling Standards",
        "tagline": "AI-Powered Sales Call Intelligence for Performance Analysis and Coaching",
        "accentColor": "#EAB308",
        "challenge": {
            "headline": "Sales Coaching Blind Spots Kill Revenue",
            "description": "Managers can only review a fraction of sales calls, leaving critical behavioural patterns invisible and coaching decisions based on guesswork. Without consistent, structured feedback at scale, training fades fast and sales performance stays unpredictable.",
            "screenshot": "customers/gold-selling-standards/1.png"
        },
        "features": [
            {
                "screenshot": "customers/gold-selling-standards/2.png",
                "label": "Sales Training Pain Points"
            },
            {
                "screenshot": "customers/gold-selling-standards/3.png",
                "label": "Execution Standards Positioning"
            },
            {
                "screenshot": "customers/gold-selling-standards/4.png",
                "label": "Three-Stage Programme Flow"
            },
            {
                "screenshot": "customers/gold-selling-standards/5.png",
                "label": "Team Outcomes Overview"
            },
            {
                "screenshot": "customers/gold-selling-standards/6.png",
                "label": "Proof in the Pipeline"
            }
        ],
        "result": {
            "headline": "18% Increase in Deal Value in 90 Days",
            "stats": [
                {
                    "value": "18%",
                    "label": "Increase in Deal Value"
                },
                {
                    "value": "90 Days",
                    "label": "Time to Results"
                },
                {
                    "value": "100%",
                    "label": "Call Coverage"
                }
            ],
            "quote": "Gold Selling Standards has helped organisations move beyond limited call sampling, enabling more consistent evaluation and scalable coaching based on real interactions — not selective review.",
            "authorName": "Gold Selling Standards",
            "authorTitle": "Sales Enablement / Conversation Intelligence",
            "screenshot": "customers/gold-selling-standards/7.png"
        }
    },
  },
  {
    id: "HgGarage",
    folder: "hg-garage",
    data: {
        "customerName": "HG Garage",
        "tagline": "Automated inventory management for automotive parts suppliers",
        "accentColor": "#F97316",
        "challenge": {
            "headline": "Spreadsheets can't keep up with multi-channel parts",
            "description": "Automotive parts suppliers were managing inventory, COGS, and financials manually across disconnected systems — leading to stock errors, duplicate data entry, and zero visibility into profitability. Sales, inventory, and financial data lived in separate silos with no unified view.",
            "screenshot": "customers/hg-garage/1.png"
        },
        "features": [
            {
                "screenshot": "customers/hg-garage/2.png",
                "label": "Parts Marketplace Listings"
            },
            {
                "screenshot": "customers/hg-garage/3.png",
                "label": "Shop by Brand"
            },
            {
                "screenshot": "customers/hg-garage/4.png",
                "label": "Customer Testimonials"
            },
            {
                "screenshot": "customers/hg-garage/5.png",
                "label": "Filtered Parts Catalog"
            },
            {
                "screenshot": "customers/hg-garage/6.png",
                "label": "Brand Story Page"
            }
        ],
        "result": {
            "headline": "Streamlined operations, confident growth",
            "stats": [
                {
                    "value": "Zero",
                    "label": "Manual Tracking"
                },
                {
                    "value": "100%",
                    "label": "Channel Sync"
                },
                {
                    "value": "1",
                    "label": "Unified Platform"
                }
            ],
            "quote": "HG Garage transformed inventory operations into a more streamlined and scalable process, empowering businesses to operate with greater confidence and efficiency.",
            "authorName": "HG Garage",
            "authorTitle": "E-commerce / Automotive Parts Supply",
            "screenshot": "customers/hg-garage/7.png"
        }
    },
  },
  {
    id: "Insidermemes",
    folder: "insidermemes",
    data: {
        "customerName": "Insidermemes",
        "tagline": "AI-Powered Meme Generator for Viral Content Creation",
        "accentColor": "#EC4899",
        "challenge": {
            "headline": "Creating timely memes takes too long",
            "description": "Content creators and brands struggled to find suitable templates, align text correctly, and produce memes quickly enough to stay relevant to trends. These barriers slowed content production and caused creators to miss fast-moving online moments.",
            "screenshot": "customers/insidermemes/1.png"
        },
        "features": [
            {
                "screenshot": "customers/insidermemes/2.png",
                "label": "Video Meme Templates"
            },
            {
                "screenshot": "customers/insidermemes/3.png",
                "label": "Image Meme Library"
            },
            {
                "screenshot": "customers/insidermemes/4.png",
                "label": "AI Meme Generator"
            },
            {
                "screenshot": "customers/insidermemes/5.png",
                "label": "Social Proof Stats"
            }
        ],
        "result": {
            "headline": "Driving Millions of Views a Day",
            "stats": [
                {
                    "value": "Seconds",
                    "label": "Idea to Finished Meme"
                },
                {
                    "value": "200M+",
                    "label": "Monthly Impressions"
                },
                {
                    "value": "Zero",
                    "label": "Design Skills Required"
                }
            ],
            "quote": "Users go from idea to finished meme in seconds, not minutes of manual editing. Brands and creators can publish timely meme content before internet moments fade.",
            "authorName": "Insidermemes",
            "authorTitle": "AI Content Creation / Social Media",
            "screenshot": "customers/insidermemes/6.png"
        }
    },
  },
  {
    id: "Notifier",
    folder: "notifier",
    data: {
        "customerName": "Notifier",
        "tagline": "AI-Powered Social Listening and Brand Monitoring Platform",
        "accentColor": "#06B6D4",
        "challenge": {
            "headline": "Brands miss critical conversations happening online",
            "description": "Organizations faced limited visibility into social media discussions influencing customer perception and market positioning. Delayed awareness of emerging issues reduced opportunities to engage proactively and protect brand reputation.",
            "screenshot": "customers/notifier/1.png"
        },
        "features": [
            {
                "screenshot": "customers/notifier/2.png",
                "label": "Downtime Pain Points"
            },
            {
                "screenshot": "customers/notifier/3.png",
                "label": "24/7 Auto Monitoring"
            },
            {
                "screenshot": "customers/notifier/4.png",
                "label": "Core Features Overview"
            },
            {
                "screenshot": "customers/notifier/5.png",
                "label": "Multi-Channel Integrations"
            },
            {
                "screenshot": "customers/notifier/6.png",
                "label": "Bootstrapped Founder Story"
            },
            {
                "screenshot": "customers/notifier/7.png",
                "label": "Product Values & Principles"
            },
            {
                "screenshot": "customers/notifier/8.png",
                "label": "Customer Testimonials"
            }
        ],
        "result": {
            "headline": "Social listening transformed into actionable intelligence",
            "stats": [
                {
                    "value": "24/7",
                    "label": "Continuous Monitoring"
                },
                {
                    "value": "Zero",
                    "label": "Missed Mentions"
                },
                {
                    "value": "AI",
                    "label": "Sentiment Analysis"
                }
            ],
            "quote": "Notifier has transformed social listening from a resource-intensive process into a more efficient and actionable capability that helps organizations stay connected with their audiences and adapt to an evolving digital landscape.",
            "authorName": "Notifier",
            "authorTitle": "Social Media Analytics & Brand Management",
            "screenshot": "customers/notifier/9.png"
        }
    },
  },
  {
    id: "Samwise",
    folder: "samwise",
    data: {
        "customerName": "Samwise AI",
        "tagline": "AI-Powered Federal Contracting Platform for Government Opportunities",
        "accentColor": "#14B8A6",
        "challenge": {
            "headline": "Drowning in Federal Contracting Noise",
            "description": "Government contractors spend countless hours sifting through high volumes of opportunities across multiple sources, making it nearly impossible to focus on the most valuable pursuits. Manual research and evaluation drain resources while teams struggle to keep pace with new opportunities.",
            "screenshot": "customers/samwise/1.png"
        },
        "features": [
            {
                "screenshot": "customers/samwise/2.png",
                "label": "AI Capability Stack"
            },
            {
                "screenshot": "customers/samwise/3.png",
                "label": "AI + Human Expertise"
            },
            {
                "screenshot": "customers/samwise/4.png",
                "label": "All-Inclusive Access Plan"
            }
        ],
        "result": {
            "headline": "Contractors Win More and Work Less",
            "stats": [
                {
                    "value": "40%",
                    "label": "Higher win rates for clients"
                },
                {
                    "value": "30+ hrs",
                    "label": "Saved per week on research"
                },
                {
                    "value": "300%",
                    "label": "Average ROI within first year"
                }
            ],
            "quote": "By simplifying opportunity discovery and analysis, Samwise AI helps contractors focus more time on strategic growth and proposal development.",
            "authorName": "Samwise AI",
            "authorTitle": "Federal Contracting / GovTech SaaS Platform",
            "screenshot": "customers/samwise/5.png"
        }
    },
  },
  {
    id: "Scoutside",
    folder: "scoutside",
    data: {
        "customerName": "Scoutside",
        "tagline": "AI-Powered College Lacrosse Recruiting Platform",
        "accentColor": "#22C55E",
        "challenge": {
            "headline": "Recruiting Is Overwhelming Without Direction",
            "description": "Student-athletes struggle to identify opportunities that align with their goals and potential. The lack of accessible insights and structured guidance leads to inefficient decision-making and missed opportunities.",
            "screenshot": "customers/scoutside/1.png"
        },
        "features": [
            {
                "screenshot": "customers/scoutside/2.png",
                "label": "Value Proposition Page"
            },
            {
                "screenshot": "customers/scoutside/3.png",
                "label": "Athlete Profile Setup"
            },
            {
                "screenshot": "customers/scoutside/4.png",
                "label": "Recruiting Dashboard"
            },
            {
                "screenshot": "customers/scoutside/5.png",
                "label": "Recruiting Fit Factors"
            },
            {
                "screenshot": "customers/scoutside/6.png",
                "label": "Platform Value Pitch"
            },
            {
                "screenshot": "customers/scoutside/7.png",
                "label": "Next Steps Guidance"
            }
        ],
        "result": {
            "headline": "Athletes Recruit With Clarity and Confidence",
            "stats": [
                {
                    "value": "AI",
                    "label": "Intelligent School Matching"
                },
                {
                    "value": "100%",
                    "label": "Personalized Fit Scoring"
                },
                {
                    "value": "Zero",
                    "label": "Guesswork in the Process"
                }
            ],
            "quote": "Scoutside delivers a more confident and structured path through the recruiting process. Athletes are better equipped to evaluate opportunities, focus their efforts more effectively, and make informed decisions about their future.",
            "authorName": "Scoutside",
            "authorTitle": "Sports Recruiting Technology",
            "screenshot": "customers/scoutside/8.png"
        }
    },
  },
  {
    id: "StammerAi",
    folder: "stammer-ai",
    data: {
        "customerName": "Stammer AI",
        "tagline": "AI-Powered White Label Platform for Conversational AI Agents",
        "accentColor": "#A855F7",
        "challenge": {
            "headline": "Building AI agents required expensive dev teams",
            "description": "The market offered two bad choices: prohibitively expensive custom AI builds requiring dedicated engineering teams, or consumer-grade chatbots too limited for enterprise use. Agencies had no practical way to package and resell AI agents as their own product, leaving a massive revenue opportunity untapped.",
            "screenshot": "customers/stammer-ai/1.png"
        },
        "features": [
            {
                "screenshot": "customers/stammer-ai/2.png",
                "label": "Multi-Channel AI Deployment"
            },
            {
                "screenshot": "customers/stammer-ai/3.png",
                "label": "Agency Social Proof"
            },
            {
                "screenshot": "customers/stammer-ai/4.png",
                "label": "White Label Voice & Chat"
            },
            {
                "screenshot": "customers/stammer-ai/5.png",
                "label": "Tech Stack Integrations"
            },
            {
                "screenshot": "customers/stammer-ai/6.png",
                "label": "Self-Serve Reseller Signup"
            }
        ],
        "result": {
            "headline": "New AI revenue streams, launched in hours",
            "stats": [
                {
                    "value": "Zero",
                    "label": "Code Required"
                },
                {
                    "value": "12M+",
                    "label": "Conversations Handled"
                },
                {
                    "value": "99.9%",
                    "label": "Uptime"
                }
            ],
            "quote": "Businesses and agencies can now build sophisticated AI agents without any programming expertise, slashing time-to-market from months to hours. Partners deliver fully white-labeled solutions that reinforce their brand and open profitable new revenue streams.",
            "authorName": "Stammer AI",
            "authorTitle": "White-Label AI Chatbot & Voice Agent Platform",
            "screenshot": "customers/stammer-ai/7.png"
        }
    },
  },
  {
    id: "Talentar",
    folder: "talentar",
    data: {
        "customerName": "TalentArc",
        "tagline": "AI-Powered Recruitment Platform for Smarter Hiring",
        "accentColor": "#0EA5E9",
        "challenge": {
            "headline": "Manual screening buries recruiters in applicant overload",
            "description": "Organizations struggle to efficiently manage high volumes of applicants while maintaining consistency and quality in hiring. Candidates experience delays and limited feedback, creating a disconnected hiring experience for everyone involved.",
            "screenshot": "customers/talentar/1.png"
        },
        "features": [
            {
                "screenshot": "customers/talentar/2.png",
                "label": "Hiring Stats & Social Proof"
            },
            {
                "screenshot": "customers/talentar/3.png",
                "label": "AI Beta Features Overview"
            },
            {
                "screenshot": "customers/talentar/4.png",
                "label": "AI Candidate Analysis"
            },
            {
                "screenshot": "customers/talentar/5.png",
                "label": "Job Seeker Opportunities"
            },
            {
                "screenshot": "customers/talentar/6.png",
                "label": "Candidate Onboarding Flow"
            },
            {
                "screenshot": "customers/talentar/7.png",
                "label": "Professional Value Props"
            }
        ],
        "result": {
            "headline": "Faster hiring, stronger matches, better experience",
            "stats": [
                {
                    "value": "95%",
                    "label": "Match Accuracy"
                },
                {
                    "value": "75%",
                    "label": "Faster Hiring"
                },
                {
                    "value": "AI",
                    "label": "Candidate Scoring"
                }
            ],
            "quote": "Recruiters benefit from significantly reduced screening effort and more structured shortlisting processes, while candidates receive faster and more relevant engagement.",
            "authorName": "TalentArc",
            "authorTitle": "AI Recruitment & HR Technology",
            "screenshot": "customers/talentar/8.png"
        }
    },
  },
  {
    id: "Zinng",
    folder: "zinng",
    data: {
        "customerName": "Zinng AI",
        "tagline": "AI-powered customer communication platform for small businesses",
        "accentColor": "#F43F5E",
        "challenge": {
            "headline": "Missed calls mean lost customers for small businesses",
            "description": "Small businesses couldn't respond to every inquiry in real time — after-hours calls went unanswered and potential customers moved on. Communication across multiple channels lacked a unified view, making consistency and visibility nearly impossible.",
            "screenshot": "customers/zinng/4.png"
        },
        "features": [
            {
                "screenshot": "customers/zinng/5.png",
                "label": "Problem vs. Solution"
            },
            {
                "screenshot": "customers/zinng/6.png",
                "label": "Full Feature Suite"
            },
            {
                "screenshot": "customers/zinng/7.png",
                "label": "4-Step Onboarding"
            },
            {
                "screenshot": "customers/zinng/8.png",
                "label": "Customer Testimonials"
            }
        ],
        "result": {
            "headline": "24/7 availability, zero missed opportunities",
            "stats": [
                {
                    "value": "24/7",
                    "label": "Customer Availability"
                },
                {
                    "value": "Zero",
                    "label": "Missed Leads"
                },
                {
                    "value": "5 min",
                    "label": "Faster Response Time"
                }
            ],
            "quote": "Zinng AI transformed how small businesses approach customer communication by helping them stay connected, responsive, and better equipped to serve their customers.",
            "authorName": "Zinng AI",
            "authorTitle": "AI Customer Communication Platform",
            "screenshot": "customers/zinng/9.png"
        }
    },
  },
];
