// AUTO-GENERATED by scripts/generate-compositions.mjs — do not edit by hand
// Run: npm run gen
import type { CustomerStoryData } from "./CustomerStory/schema";

export const CUSTOMERS: Array<{ id: string; folder: string; data: CustomerStoryData }> = [
  {
    id: "Alertora",
    folder: "alertora",
    data: {
        "customerName": "Alertora",
        "tagline": "AI-Powered WhatsApp Safety Companion for Solo Travelers",
        "websiteUrl": "alertora.com",
        "accentColor": "#10B981",
        "challenge": {
            "headline": "Solo travelers overwhelmed by fragmented info",
            "description": "Solo travelers relied on scattered sources to find destination-specific guidance, making quick access to help stressful and time-consuming. There was no single, familiar channel that could deliver calm, personalized support exactly when it was needed most.",
            "screenshot": "customers/alertora/1.png"
        },
        "features": [
            {
                "screenshot": "customers/alertora/2.png",
                "label": "Real Traveler Scenarios"
            },
            {
                "screenshot": "customers/alertora/3.png",
                "label": "3-Step Onboarding Flow"
            },
            {
                "screenshot": "customers/alertora/4.png",
                "label": "Safety Features Grid"
            },
            {
                "screenshot": "customers/alertora/5.png",
                "label": "Community Growth Stats"
            }
        ],
        "result": {
            "headline": "Confident solo travel, delivered via WhatsApp",
            "stats": [
                {
                    "value": "1,000+",
                    "label": "Solo Travelers Joined"
                },
                {
                    "value": "24/7",
                    "label": "Always-On Support"
                },
                {
                    "value": "180+",
                    "label": "Destinations Covered"
                }
            ],
            "quote": "Alertora made me feel like I had a friend watching out for me the entire trip. The check-ins after every activity gave me so much peace of mind.",
            "authorName": "Alertora",
            "authorTitle": "Travel Safety / AI Chatbots",
            "screenshot": "customers/alertora/6.png"
        }
    },
  },
  {
    id: "Axirify",
    folder: "axirify",
    data: {
        "customerName": "Axirify",
        "tagline": "The WhatsApp-First Automation Platform for Clinics & Med Spas",
        "websiteUrl": "axirify.com",
        "accentColor": "#6366F1",
        "challenge": {
            "headline": "Manual Processes Are Costing Clinics Every Day",
            "description": "Clinics rely on disconnected tools and manual follow-ups, causing delayed responses, missed appointments, and lost revenue. Staff spend hours on routine tasks that should be automated.",
            "screenshot": "customers/axirify/1.png"
        },
        "features": [
            {
                "screenshot": "customers/axirify/2.png",
                "label": "Unified Operations Dashboard"
            },
            {
                "screenshot": "customers/axirify/3.png",
                "label": "Pain Points Overview"
            },
            {
                "screenshot": "customers/axirify/4.png",
                "label": "Front Office Automation"
            },
            {
                "screenshot": "customers/axirify/5.png",
                "label": "4-Step Automation Workflow"
            },
            {
                "screenshot": "customers/axirify/6.png",
                "label": "WhatsApp & Stripe Integrations"
            }
        ],
        "result": {
            "headline": "5x ROI and 40+ Hours Saved Every Month",
            "stats": [
                {
                    "value": "5x",
                    "label": "Total ROI (conservative estimate)"
                },
                {
                    "value": "40+",
                    "label": "Hours saved per month"
                },
                {
                    "value": "100+",
                    "label": "More appointments confirmed"
                }
            ],
            "quote": "One client recovered +$5,000 USD/month in lost appointments from faster follow-ups alone.",
            "authorName": "Axirify",
            "authorTitle": "Clinics & Med Spas",
            "screenshot": "customers/axirify/7.png"
        }
    },
  },
  {
    id: "BacklinkBrain",
    folder: "backlink-brain",
    data: {
        "customerName": "Backlink Brain",
        "tagline": "Swipe Left, Swipe Right, Build Backlinks",
        "websiteUrl": "backlinkbrain.com",
        "accentColor": "#F59E0B",
        "challenge": {
            "headline": "Backlink Outreach Was Drowning in Manual Work",
            "description": "SEO professionals and agencies were juggling multiple tools and repetitive processes just to identify opportunities and manage outreach campaigns at scale. The lack of a unified workflow created bottlenecks that limited efficiency and made it impossible to grow.",
            "screenshot": "customers/backlink-brain/1.png"
        },
        "features": [
            {
                "screenshot": "customers/backlink-brain/2.png",
                "label": "Mobile App Hero"
            },
            {
                "screenshot": "customers/backlink-brain/3.png",
                "label": "Campaign Dashboard View"
            },
            {
                "screenshot": "customers/backlink-brain/4.png",
                "label": "Homepage Overview"
            },
            {
                "screenshot": "customers/backlink-brain/5.png",
                "label": "App Download Landing"
            },
            {
                "screenshot": "customers/backlink-brain/6.png",
                "label": "PitchBox Integration"
            },
            {
                "screenshot": "customers/backlink-brain/7.png",
                "label": "3-Step Onboarding Flow"
            },
            {
                "screenshot": "customers/backlink-brain/8.png",
                "label": "Benefits & Audience Section"
            },
            {
                "screenshot": "customers/backlink-brain/9.png",
                "label": "User Success Stories"
            },
            {
                "screenshot": "customers/backlink-brain/10.png",
                "label": "Contact Data Discovery"
            }
        ],
        "result": {
            "headline": "Launched on Web & Mobile, Scaling SEO Teams",
            "stats": [
                {
                    "value": "10+ hrs/wk",
                    "label": "Saved finding leads"
                },
                {
                    "value": "10 pts",
                    "label": "DR increase for users"
                },
                {
                    "value": "10+ hrs/wk",
                    "label": "Saved writing cold emails"
                }
            ],
            "quote": "Backlink Brain simplifies and modernizes outreach workflows, enabling teams to focus more on strategy and relationship-building rather than repetitive operational tasks.",
            "authorName": "Backlink Brain",
            "authorTitle": "SEO / AI Marketing Platform",
            "screenshot": "customers/backlink-brain/11.png"
        }
    },
  },
  {
    id: "CeTax",
    folder: "ce-tax",
    data: {
        "customerName": "CE Tax",
        "tagline": "Unified financial management system for invoicing, transactions & compliance",
        "websiteUrl": "cetax.com",
        "accentColor": "#3B82F6",
        "challenge": {
            "headline": "Fragmented finance tools create costly gaps",
            "description": "Growing businesses managed invoices, transactions, and reporting across separate disconnected tools — creating administrative overhead and limiting financial visibility. The fragmentation made it difficult to maintain accurate, timely financial records at scale.",
            "screenshot": "customers/ce-tax/1.png"
        },
        "features": [
            {
                "screenshot": "customers/ce-tax/2.png",
                "label": "Unified Features Overview"
            }
        ],
        "result": {
            "headline": "Centralized, confident financial management",
            "stats": [
                {
                    "value": "1",
                    "label": "Unified Platform"
                },
                {
                    "value": "Zero",
                    "label": "Fragmented Processes"
                },
                {
                    "value": "100%",
                    "label": "Centralized Records"
                }
            ],
            "quote": "CE Tax enables businesses to work more effectively and maintain greater confidence in their financial operations.",
            "authorName": "CE Tax",
            "authorTitle": "Tax & Compliance Financial Software",
            "screenshot": "customers/ce-tax/3.png"
        }
    },
  },
  {
    id: "Celleasy",
    folder: "celleasy",
    data: {
        "customerName": "CellEasy",
        "tagline": "E-commerce platform for Rogers dealers with sales attribution & tracking",
        "websiteUrl": "celleasy.com",
        "accentColor": "#EF4444",
        "challenge": {
            "headline": "No way to track which rep made each online sale",
            "description": "Standard e-commerce platforms couldn't attribute sales to individual representatives, making it impossible for Rogers dealers to measure team performance or distribute commissions fairly. Managing complex telecom product catalogs with carrier plans, devices, and accessories added further operational strain.",
            "screenshot": "customers/celleasy/1.png"
        },
        "features": [
            {
                "screenshot": "customers/celleasy/2.png",
                "label": "Featured Deals Showcase"
            },
            {
                "screenshot": "customers/celleasy/3.png",
                "label": "Customer Navigation Hub"
            }
        ],
        "result": {
            "headline": "Digital commerce built for dealer teams",
            "stats": [
                {
                    "value": "100%",
                    "label": "Sales Attribution"
                },
                {
                    "value": "Zero",
                    "label": "Commission Disputes"
                },
                {
                    "value": "1",
                    "label": "Unified Platform"
                }
            ],
            "quote": "CellEasy bridged the gap between traditional retail sales structures and digital commerce, improving visibility into team performance and creating a more structured and scalable approach to wireless retail distribution.",
            "authorName": "CellEasy",
            "authorTitle": "Wireless Retail E-Commerce Platform",
            "screenshot": "customers/celleasy/4.png"
        }
    },
  },
  {
    id: "Dare",
    folder: "dare",
    data: {
        "customerName": "DARE",
        "tagline": "Agentic AI Research Platform for Scientists and PhD Researchers",
        "websiteUrl": "dare.ai",
        "accentColor": "#8B5CF6",
        "challenge": {
            "headline": "Advanced AI was locked behind engineering expertise",
            "description": "Scientists who needed AI agents to process massive datasets or run complex analysis workflows faced steep technical barriers without dedicated engineering support. Sending sensitive research data to commercial AI platforms also violated institutional data policies.",
            "screenshot": "customers/dare/1.png"
        },
        "features": [
            {
                "screenshot": "customers/dare/2.png",
                "label": "Self-Hosted Architecture"
            },
            {
                "screenshot": "customers/dare/3.png",
                "label": "Multi-Audience Platform"
            },
            {
                "screenshot": "customers/dare/4.png",
                "label": "Workflow Builder Tools"
            }
        ],
        "result": {
            "headline": "AI research democratized at Carnegie Mellon",
            "stats": [
                {
                    "value": "2,000+",
                    "label": "Students Served"
                },
                {
                    "value": "Multi-school",
                    "label": "Collaborations Underway"
                },
                {
                    "value": "100%",
                    "label": "Data Stays In-House"
                }
            ],
            "quote": "DARE has transformed AI-powered research from an engineering challenge into an accessible tool for scientific discovery. Deployed at Carnegie Mellon University, it now accelerates AI-powered research across multiple disciplines.",
            "authorName": "DARE",
            "authorTitle": "AI Research Platform, Academia & Non-Profits",
            "screenshot": "customers/dare/5.png"
        }
    },
  },
  {
    id: "GoldSellingStandards",
    folder: "gold-selling-standards",
    data: {
        "customerName": "Gold Selling Standards",
        "tagline": "AI-Powered Sales Call Intelligence for Performance Analysis and Coaching",
        "websiteUrl": "goldsellingstandards.com",
        "accentColor": "#EAB308",
        "challenge": {
            "headline": "Sales Coaching Blind Spots Kill Revenue",
            "description": "Managers can only review a fraction of sales calls, leaving critical behavioural patterns invisible and coaching decisions based on guesswork. Without consistent, structured feedback at scale, training fades fast and sales performance stays unpredictable.",
            "screenshot": "customers/gold-selling-standards/1.png"
        },
        "features": [
            {
                "screenshot": "customers/gold-selling-standards/2.png",
                "label": "Sales Training Pain Points"
            },
            {
                "screenshot": "customers/gold-selling-standards/3.png",
                "label": "Execution Standards Positioning"
            },
            {
                "screenshot": "customers/gold-selling-standards/4.png",
                "label": "Three-Stage Programme Flow"
            },
            {
                "screenshot": "customers/gold-selling-standards/5.png",
                "label": "Team Outcomes Overview"
            },
            {
                "screenshot": "customers/gold-selling-standards/6.png",
                "label": "Proof in the Pipeline"
            }
        ],
        "result": {
            "headline": "18% Increase in Deal Value in 90 Days",
            "stats": [
                {
                    "value": "18%",
                    "label": "Increase in Deal Value"
                },
                {
                    "value": "90 Days",
                    "label": "Time to Results"
                },
                {
                    "value": "100%",
                    "label": "Call Coverage"
                }
            ],
            "quote": "Gold Selling Standards has helped organisations move beyond limited call sampling, enabling more consistent evaluation and scalable coaching based on real interactions — not selective review.",
            "authorName": "Gold Selling Standards",
            "authorTitle": "Sales Enablement / Conversation Intelligence",
            "screenshot": "customers/gold-selling-standards/7.png"
        }
    },
  },
  {
    id: "HgGarage",
    folder: "hg-garage",
    data: {
        "customerName": "HG Garage",
        "tagline": "Automated inventory management for automotive parts suppliers",
        "websiteUrl": "hggarage.com",
        "accentColor": "#F97316",
        "challenge": {
            "headline": "Spreadsheets can't keep up with multi-channel parts",
            "description": "Automotive parts suppliers were managing inventory, COGS, and financials manually across disconnected systems — leading to stock errors, duplicate data entry, and zero visibility into profitability. Sales, inventory, and financial data lived in separate silos with no unified view.",
            "screenshot": "customers/hg-garage/1.png"
        },
        "features": [
            {
                "screenshot": "customers/hg-garage/2.png",
                "label": "Parts Marketplace Listings"
            },
            {
                "screenshot": "customers/hg-garage/3.png",
                "label": "Shop by Brand"
            },
            {
                "screenshot": "customers/hg-garage/4.png",
                "label": "Customer Testimonials"
            },
            {
                "screenshot": "customers/hg-garage/5.png",
                "label": "Filtered Parts Catalog"
            },
            {
                "screenshot": "customers/hg-garage/6.png",
                "label": "Brand Story Page"
            }
        ],
        "result": {
            "headline": "Streamlined operations, confident growth",
            "stats": [
                {
                    "value": "Zero",
                    "label": "Manual Tracking"
                },
                {
                    "value": "100%",
                    "label": "Channel Sync"
                },
                {
                    "value": "1",
                    "label": "Unified Platform"
                }
            ],
            "quote": "HG Garage transformed inventory operations into a more streamlined and scalable process, empowering businesses to operate with greater confidence and efficiency.",
            "authorName": "HG Garage",
            "authorTitle": "E-commerce / Automotive Parts Supply",
            "screenshot": "customers/hg-garage/7.png"
        }
    },
  },
  {
    id: "Insidermemes",
    folder: "insidermemes",
    data: {
        "customerName": "Insidermemes",
        "tagline": "AI-Powered Meme Generator for Viral Content Creation",
        "websiteUrl": "insidermemes.com",
        "accentColor": "#EC4899",
        "challenge": {
            "headline": "Creating timely memes takes too long",
            "description": "Content creators and brands struggled to find suitable templates, align text correctly, and produce memes quickly enough to stay relevant to trends. These barriers slowed content production and caused creators to miss fast-moving online moments.",
            "screenshot": "customers/insidermemes/1.png"
        },
        "features": [
            {
                "screenshot": "customers/insidermemes/2.png",
                "label": "Video Meme Templates"
            },
            {
                "screenshot": "customers/insidermemes/3.png",
                "label": "Image Meme Library"
            },
            {
                "screenshot": "customers/insidermemes/4.png",
                "label": "AI Meme Generator"
            },
            {
                "screenshot": "customers/insidermemes/5.png",
                "label": "Social Proof Stats"
            }
        ],
        "result": {
            "headline": "Driving Millions of Views a Day",
            "stats": [
                {
                    "value": "Seconds",
                    "label": "Idea to Finished Meme"
                },
                {
                    "value": "200M+",
                    "label": "Monthly Impressions"
                },
                {
                    "value": "Zero",
                    "label": "Design Skills Required"
                }
            ],
            "quote": "Users go from idea to finished meme in seconds, not minutes of manual editing. Brands and creators can publish timely meme content before internet moments fade.",
            "authorName": "Insidermemes",
            "authorTitle": "AI Content Creation / Social Media",
            "screenshot": "customers/insidermemes/6.png"
        }
    },
  },
  {
    id: "Notifier",
    folder: "notifier",
    data: {
        "customerName": "Notifier",
        "tagline": "AI-Powered Social Listening and Brand Monitoring Platform",
        "websiteUrl": "notifier.com",
        "accentColor": "#06B6D4",
        "challenge": {
            "headline": "Brands Blind to Conversations That Shape Them",
            "description": "Organizations struggled with limited visibility into social media discussions that could influence brand perception and customer satisfaction. Delayed awareness of important conversations reduced opportunities to respond proactively and protect brand reputation.",
            "screenshot": "customers/notifier/1.png"
        },
        "features": [
            {
                "screenshot": "customers/notifier/2.png",
                "label": "Downtime Risk Breakdown"
            },
            {
                "screenshot": "customers/notifier/3.png",
                "label": "24/7 Site Monitoring"
            },
            {
                "screenshot": "customers/notifier/4.png",
                "label": "Features Overview"
            },
            {
                "screenshot": "customers/notifier/5.png",
                "label": "Integrations Grid"
            },
            {
                "screenshot": "customers/notifier/6.png",
                "label": "Founder Story Section"
            }
        ],
        "result": {
            "headline": "Social Listening Transformed Into Actionable Insight",
            "stats": [
                {
                    "value": "Real-Time",
                    "label": "Brand Monitoring"
                },
                {
                    "value": "AI-Powered",
                    "label": "Sentiment Analysis"
                },
                {
                    "value": "Faster",
                    "label": "Team Response Times"
                }
            ],
            "quote": "Notifier has transformed social listening from a resource-intensive process into a more efficient and actionable capability that helps organizations stay connected with their audiences and adapt to an evolving digital landscape.",
            "authorName": "Notifier",
            "authorTitle": "Social Media Analytics & Brand Management",
            "screenshot": "customers/notifier/7.png"
        }
    },
  },
  {
    id: "OneaiHealth",
    folder: "oneai-health",
    data: {
        "customerName": "ONEai Health",
        "tagline": "AI-Powered Chronic Care Intelligence — Continuous, Measurable, Actionable",
        "websiteUrl": "oneaihealth.com",
        "accentColor": "#0EA5E9",
        "challenge": {
            "headline": "Risk Compounds Silently Between Clinic Visits",
            "description": "96% of a patient's health journey happens outside the clinic, yet traditional care models only capture the 4% that occurs in-office. Healthcare organizations managing chronic care programs lack a unified view of patient status, making it nearly impossible to prioritize interventions before conditions escalate.",
            "screenshot": "customers/oneai-health/1.png"
        },
        "features": [
            {
                "screenshot": "customers/oneai-health/2.png",
                "label": "Between-Visit Gap Stats"
            },
            {
                "screenshot": "customers/oneai-health/3.png",
                "label": "Care Network Platform"
            },
            {
                "screenshot": "customers/oneai-health/4.png",
                "label": "Ecosystem Intelligence"
            },
            {
                "screenshot": "customers/oneai-health/5.png",
                "label": "Patient Engagement Hub"
            }
        ],
        "result": {
            "headline": "Decision-Ready Intelligence Delivered at Scale",
            "stats": [
                {
                    "value": "96%",
                    "label": "of care happens between visits — now monitored"
                },
                {
                    "value": "2-in-1",
                    "label": "Continuous + Predictive Care Intelligence layers"
                },
                {
                    "value": "360°",
                    "label": "Unified view across patients, clinicians & payers"
                }
            ],
            "quote": "By bringing patient engagement, care coordination, and health insights together within a single platform, ONEai Health helps healthcare organizations deliver a more connected and proactive care experience.",
            "authorName": "ONEai Health",
            "authorTitle": "AI Healthcare / Digital Health",
            "screenshot": "customers/oneai-health/6.png"
        }
    },
  },
  {
    id: "SalesedgeAi",
    folder: "salesedge-ai",
    data: {
        "customerName": "SalesEdgeAI",
        "tagline": "AI-powered sales automation that eliminates post-meeting admin work",
        "websiteUrl": "salesedgeai.com",
        "accentColor": "#8B5CF6",
        "challenge": {
            "headline": "Sales reps lose 30% of selling time to admin",
            "description": "Sales professionals were drowning in manual CRM updates, disconnected follow-ups, and lost conversation insights after every client meeting. Without an intelligent layer connecting their tools, deals slipped through the cracks and forecasting accuracy eroded.",
            "screenshot": "customers/salesedge-ai/1.png"
        },
        "features": [
            {
                "screenshot": "customers/salesedge-ai/2.png",
                "label": "AI Sales Partner Dashboard"
            },
            {
                "screenshot": "customers/salesedge-ai/3.png",
                "label": "Fragmentation Cost Stats"
            },
            {
                "screenshot": "customers/salesedge-ai/4.png",
                "label": "Meeting Intelligence Insights"
            },
            {
                "screenshot": "customers/salesedge-ai/5.png",
                "label": "Revenue Leakage Calculator"
            }
        ],
        "result": {
            "headline": "8–10 hours recovered per rep, every week",
            "stats": [
                {
                    "value": "8-10 hrs",
                    "label": "Recovered per rep weekly"
                },
                {
                    "value": "40%",
                    "label": "Improvement in follow-up consistency"
                },
                {
                    "value": "Real-time",
                    "label": "CRM data with zero manual input"
                }
            ],
            "quote": "SalesEdgeAI operates in the background, eliminating manual overhead so sales teams stay focused entirely on customer engagement and closing deals.",
            "authorName": "SalesEdgeAI",
            "authorTitle": "AI Sales Automation",
            "screenshot": "customers/salesedge-ai/6.png"
        }
    },
  },
  {
    id: "Samwise",
    folder: "samwise",
    data: {
        "customerName": "Samwise AI",
        "tagline": "AI-Powered Federal Contracting Platform for Government Opportunities",
        "websiteUrl": "samwiseai.com",
        "accentColor": "#14B8A6",
        "challenge": {
            "headline": "Manual Research Drains Time on Federal Contracts",
            "description": "Government contractors faced an overwhelming volume of opportunities scattered across multiple sources, making it nearly impossible to focus on the right pursuits. Teams spent excessive hours on manual research and evaluation, leaving little time for strategic proposal development.",
            "screenshot": "customers/samwise/1.png"
        },
        "features": [
            {
                "screenshot": "customers/samwise/2.png",
                "label": "Company Profile Setup"
            },
            {
                "screenshot": "customers/samwise/3.png",
                "label": "All-Inclusive Pricing Plan"
            },
            {
                "screenshot": "customers/samwise/4.png",
                "label": "Opportunity List View"
            },
            {
                "screenshot": "customers/samwise/5.png",
                "label": "Market Analytics Dashboard"
            },
            {
                "screenshot": "customers/samwise/6.png",
                "label": "Performance Stats Overview"
            }
        ],
        "result": {
            "headline": "Contractors Win More with Less Time Wasted",
            "stats": [
                {
                    "value": "40%",
                    "label": "Higher win rates"
                },
                {
                    "value": "30+ hrs",
                    "label": "Saved per week"
                },
                {
                    "value": "300%",
                    "label": "Average ROI in year one"
                }
            ],
            "quote": "SAMwiseAI consolidates newly available, high-potential opportunities and provides data-driven insights to shape your capture strategy — giving you the competitive edge to win more business, faster.",
            "authorName": "Samwise AI",
            "authorTitle": "Federal Contracting / GovTech",
            "screenshot": "customers/samwise/7.png"
        }
    },
  },
  {
    id: "Scoutside",
    folder: "scoutside",
    data: {
        "customerName": "Scoutside",
        "tagline": "AI-Powered College Lacrosse Recruiting Platform",
        "websiteUrl": "scoutside.com",
        "accentColor": "#22C55E",
        "challenge": {
            "headline": "Recruiting Is Overwhelming Without Direction",
            "description": "Student-athletes struggle to identify opportunities that align with their goals and potential. The lack of accessible insights and structured guidance leads to inefficient decision-making and missed opportunities.",
            "screenshot": "customers/scoutside/1.png"
        },
        "features": [
            {
                "screenshot": "customers/scoutside/2.png",
                "label": "Value Proposition Page"
            },
            {
                "screenshot": "customers/scoutside/3.png",
                "label": "Athlete Profile Setup"
            },
            {
                "screenshot": "customers/scoutside/4.png",
                "label": "Recruiting Dashboard"
            },
            {
                "screenshot": "customers/scoutside/5.png",
                "label": "Recruiting Fit Factors"
            },
            {
                "screenshot": "customers/scoutside/6.png",
                "label": "Platform Value Pitch"
            },
            {
                "screenshot": "customers/scoutside/7.png",
                "label": "Next Steps Guidance"
            }
        ],
        "result": {
            "headline": "Athletes Recruit With Clarity and Confidence",
            "stats": [
                {
                    "value": "AI",
                    "label": "Intelligent School Matching"
                },
                {
                    "value": "100%",
                    "label": "Personalized Fit Scoring"
                },
                {
                    "value": "Zero",
                    "label": "Guesswork in the Process"
                }
            ],
            "quote": "Scoutside delivers a more confident and structured path through the recruiting process. Athletes are better equipped to evaluate opportunities, focus their efforts more effectively, and make informed decisions about their future.",
            "authorName": "Scoutside",
            "authorTitle": "Sports Recruiting Technology",
            "screenshot": "customers/scoutside/8.png"
        }
    },
  },
  {
    id: "StammerAi",
    folder: "stammer-ai",
    data: {
        "customerName": "Stammer AI",
        "tagline": "AI-Powered White Label Platform for Conversational AI Agents",
        "websiteUrl": "stammer.ai",
        "accentColor": "#A855F7",
        "challenge": {
            "headline": "Building AI agents required expensive dev teams",
            "description": "The market offered two bad choices: prohibitively expensive custom AI builds requiring dedicated engineering teams, or consumer-grade chatbots too limited for enterprise use. Agencies had no practical way to package and resell AI agents as their own product, leaving a massive revenue opportunity untapped.",
            "screenshot": "customers/stammer-ai/1.png"
        },
        "features": [
            {
                "screenshot": "customers/stammer-ai/2.png",
                "label": "Multi-Channel AI Deployment"
            },
            {
                "screenshot": "customers/stammer-ai/3.png",
                "label": "Agency Social Proof"
            },
            {
                "screenshot": "customers/stammer-ai/4.png",
                "label": "White Label Voice & Chat"
            },
            {
                "screenshot": "customers/stammer-ai/5.png",
                "label": "Tech Stack Integrations"
            },
            {
                "screenshot": "customers/stammer-ai/6.png",
                "label": "Self-Serve Reseller Signup"
            }
        ],
        "result": {
            "headline": "New AI revenue streams, launched in hours",
            "stats": [
                {
                    "value": "Zero",
                    "label": "Code Required"
                },
                {
                    "value": "12M+",
                    "label": "Conversations Handled"
                },
                {
                    "value": "99.9%",
                    "label": "Uptime"
                }
            ],
            "quote": "Businesses and agencies can now build sophisticated AI agents without any programming expertise, slashing time-to-market from months to hours. Partners deliver fully white-labeled solutions that reinforce their brand and open profitable new revenue streams.",
            "authorName": "Stammer AI",
            "authorTitle": "White-Label AI Chatbot & Voice Agent Platform",
            "screenshot": "customers/stammer-ai/7.png"
        }
    },
  },
  {
    id: "Talentar",
    folder: "talentar",
    data: {
        "customerName": "TalentArc",
        "tagline": "AI-Powered Recruitment Platform for Smarter Hiring",
        "websiteUrl": "talentarc.ai",
        "accentColor": "#0EA5E9",
        "challenge": {
            "headline": "Manual screening buries recruiters in applicant overload",
            "description": "Organizations struggle to efficiently manage high volumes of applicants while maintaining consistency and quality in hiring. Candidates experience delays and limited feedback, creating a disconnected hiring experience for everyone involved.",
            "screenshot": "customers/talentar/1.png"
        },
        "features": [
            {
                "screenshot": "customers/talentar/2.png",
                "label": "Hiring Stats & Social Proof"
            },
            {
                "screenshot": "customers/talentar/3.png",
                "label": "AI Beta Features Overview"
            },
            {
                "screenshot": "customers/talentar/4.png",
                "label": "AI Candidate Analysis"
            },
            {
                "screenshot": "customers/talentar/5.png",
                "label": "Job Seeker Opportunities"
            },
            {
                "screenshot": "customers/talentar/6.png",
                "label": "Candidate Onboarding Flow"
            },
            {
                "screenshot": "customers/talentar/7.png",
                "label": "Professional Value Props"
            }
        ],
        "result": {
            "headline": "Faster hiring, stronger matches, better experience",
            "stats": [
                {
                    "value": "95%",
                    "label": "Match Accuracy"
                },
                {
                    "value": "75%",
                    "label": "Faster Hiring"
                },
                {
                    "value": "AI",
                    "label": "Candidate Scoring"
                }
            ],
            "quote": "Recruiters benefit from significantly reduced screening effort and more structured shortlisting processes, while candidates receive faster and more relevant engagement.",
            "authorName": "TalentArc",
            "authorTitle": "AI Recruitment & HR Technology",
            "screenshot": "customers/talentar/8.png"
        }
    },
  },
  {
    id: "Zinng",
    folder: "zinng",
    data: {
        "customerName": "Zinng AI",
        "tagline": "AI-Powered Customer Communication Platform for Small Businesses",
        "websiteUrl": "zinng.ai",
        "accentColor": "#F43F5E",
        "challenge": {
            "headline": "Missed calls mean lost customers for small businesses",
            "description": "Small businesses constantly lose opportunities when calls go unanswered after hours or during busy periods, driving potential customers straight to competitors. Disconnected communication channels made it impossible to stay consistent and responsive without increasing operational burden.",
            "screenshot": "customers/zinng/1.png"
        },
        "features": [
            {
                "screenshot": "customers/zinng/2.png",
                "label": "Problem vs. Solution"
            },
            {
                "screenshot": "customers/zinng/3.png",
                "label": "Hero & Press Recognition"
            },
            {
                "screenshot": "customers/zinng/4.png",
                "label": "Full Feature Suite"
            },
            {
                "screenshot": "customers/zinng/5.png",
                "label": "4-Step Onboarding Flow"
            },
            {
                "screenshot": "customers/zinng/6.png",
                "label": "Customer Testimonials"
            }
        ],
        "result": {
            "headline": "24/7 availability, zero missed opportunities",
            "stats": [
                {
                    "value": "24/7",
                    "label": "Customer Availability"
                },
                {
                    "value": "80%",
                    "label": "Of Callers Won't Leave Voicemail"
                },
                {
                    "value": "5 min",
                    "label": "Response Time Boosts Conversion 100x"
                }
            ],
            "quote": "Zinng AI transformed how small businesses approach customer communication by helping them stay connected, responsive, and better equipped to serve their customers.",
            "authorName": "Zinng AI",
            "authorTitle": "AI Customer Communication",
            "screenshot": "customers/zinng/7.png"
        }
    },
  },
];
